#include "module1.h"
#include "hpc_helpers.hpp"
#include <cuda_runtime.h>
#include <iostream>

// ====================================================================
// DEVICE KERNEL: Executed on the GPU, computes a single element
// ====================================================================
__global__ void compute_partitions_kernel(const uint64_t* __restrict__ d_keys, 
                                          uint16_t* __restrict__ d_part_id, 
                                          size_t N, 
                                          uint32_t mask) 
{
    // 1. Calculation of the global 1D thread index
    size_t i = (size_t)blockIdx.x * blockDim.x + threadIdx.x;

    // 2. Boundary check (vital for the last block)
    if (i < N) {
        uint64_t k = d_keys[i];
        // Scalar logic identical to base C++, the GPU handles the parallelism
        d_part_id[i] = static_cast<uint16_t>((k ^ (k >> 32))) & mask;
    }
}

// ====================================================================
// HOST FUNCTION: Orchestrates transfers and kernel launch
// ====================================================================
// Added t_h2d, t_kernel, t_d2h passed by reference!
void compute_partitions_cuda(const uint64_t* h_keys, 
                             uint16_t* h_part_id, 
                             size_t N, 
                             uint32_t P,
                             float& t_h2d,
                             float& t_kernel,
                             float& t_d2h) 
{
    uint32_t mask = P - 1;
    
    uint64_t* d_keys = nullptr;
    uint16_t* d_part_id = nullptr;

    size_t bytes_keys = N * sizeof(uint64_t);
    size_t bytes_parts = N * sizeof(uint16_t);

    // 1. DEVICE ALLOCATION
    CUERR { cudaMalloc((void**)&d_keys, bytes_keys); }
    CUERR { cudaMalloc((void**)&d_part_id, bytes_parts); }

    // 2. HOST-TO-DEVICE TRANSFER (H2D)
    TIMERSTART(H2D_Transfer)
    CUERR { cudaMemcpy(d_keys, h_keys, bytes_keys, H2D); }
    TIMERSTOP(H2D_Transfer)
    // We "steal" the variable generated by the macro and pass it to the main!
    t_h2d = timeH2D_Transfer; 

    // 3. KERNEL CONFIGURATION AND LAUNCH
    int threadsPerBlock = 256;
    size_t numBlocks = SDIV(N, threadsPerBlock);

    TIMERSTART(Kernel_Execution)
    compute_partitions_kernel<<<numBlocks, threadsPerBlock>>>(d_keys, d_part_id, N, mask);
    CUERR { cudaGetLastError(); } // Check for synchronous errors during launch
    CUERR { cudaDeviceSynchronize(); } // Wait for the kernel to finish
    TIMERSTOP(Kernel_Execution)
    // Pass the kernel time to the main
    t_kernel = timeKernel_Execution;

    // 4. DEVICE-TO-HOST TRANSFER (D2H)
    TIMERSTART(D2H_Transfer)
    CUERR { cudaMemcpy(h_part_id, d_part_id, bytes_parts, D2H); }
    TIMERSTOP(D2H_Transfer)
    // Pass the copy-back time to the main
    t_d2h = timeD2H_Transfer;

    // 5. MEMORY CLEANUP
    CUERR { cudaFree(d_keys); }
    CUERR { cudaFree(d_part_id); }
}